#!/usr/bin/env python3
"""Single-case rotating-wormhole evolution driver (CLI, no per-case param files).

Mirrors the QD-campaign pattern: instead of committing a params_*.txt per case,
this generates the evolution params from one in-code template + CLI knobs, writes
it into the run directory, launches the GRTeclyn CUDA binary, and (optionally)
renders frames offline then prunes the heavy plotfiles.

The GRTresna-solved initial data is located by the same tag scheme the ID driver
(`solve_kappa_family.py`) writes:

    runs/rotating_wormhole_id/rotwh_omega_p<omega>_m<m>_kappa_<kappa>_dx<dx>/initial_data.gridinit

L2 lesson: the evolution level-0 dx must equal the gridinit's native dx, so
--dx selects BOTH (dx=1.0 -> N=64 solve, dx=0.5 -> N=128 solve).

Usage:
    wormhole_case.sh --kappa 1.0 --dx 0.5 --max-level 3 --stop-time 8 --gpu 0
    wormhole_case.sh --kappa 0.7 --dx 0.5 --gpu 1 --no-frames
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

GRTECLYN_ROOT = Path(
    os.environ.get("GRTECLYN_ROOT", "/home/jovyan/nachevsky/test/simulation/GRTeclyn")
).resolve()
EXAMPLE_DIR = GRTECLYN_ROOT / "Examples" / "RotatingWormholeCollapse"
ID_ROOT = GRTECLYN_ROOT / "runs" / "rotating_wormhole_id"
RUN_ROOT = GRTECLYN_ROOT / "runs" / "rotating_wormhole"
BIN = EXAMPLE_DIR / "main3d.gnu.MPI.CUDA.ex"
WRAPPER_SRC = Path(__file__).resolve().parents[2] / "src"

EVO_L = 64.0
CENTER = (32.0, 32.0, 0.0)
FRAME_FIELDS = "chi chi_minus_1 K lapse phi Pi phi2 Pi2 Weyl4_Re Weyl4_Im Weyl4_Mag"


def _p(x: float) -> str:
    """GRTeclyn-run tag formatting: 0.05 -> '0p05', 1.0 -> '1p00'."""
    return f"{x:.2f}".replace(".", "p")


def _dx_tag(dx: float) -> str:
    return f"dx{dx:.3g}".replace(".", "p")


def id_tag(kappa: float, omega: float, m: int, dx: float) -> str:
    # Must match solve_kappa_family.py's run_dir tag.
    return f"rotwh_omega_p{_p(omega)}_m{m}_kappa_{_p(kappa)}_{_dx_tag(dx)}"


def case_tag(kappa: float, omega: float, m: int, dx: float, max_level: int) -> str:
    return f"evo_omega_p{_p(omega)}_m{m}_kappa_{_p(kappa)}_{_dx_tag(dx)}_ml{max_level}"


PARAMS_TEMPLATE = """\
# Rotating-wormhole evolution (generated by wormhole_case.py; do not hand-edit).
# GRTresna-solved complex phantom-scalar ID, m={m}, omega={omega}, kappa={kappa}.
# Level-0 dx={dx} (N={N}, L={L}) == gridinit native dx (L2). max_level={max_level}.
verbosity = 1

output_path = "{run_out}"
amr.check_file = "{run_out}/RotatingWormholeChk"
amr.plot_file  = "{run_out}/RotatingWormholePlt"

checkpoint_interval = -1
plot_interval       = {plot_interval}

amr.plot_vars = chi K lapse shift1 shift2 shift3 phi Pi phi2 Pi2
amr.derive_plot_vars = Weyl4

hdf5_subpath = "hdf5"
pout_subpath = "pout"
data_subpath = "data"

print_progress_only_to_rank_0 = 1

recipe_initial_data_file = "{gridinit}"
wormhole_matter_model = "complex_scalar"

wormhole_initial_lapse_type = 0
wormhole_throat_radius = 0.5
wormhole_centerA = 0.0 0.0 0.0
wormhole_phi_monopole_amplitude     = 0.0
wormhole_phi_perturbation_amplitude = 0.0
wormhole_phi_perturbation_width     = 0.5
wormhole_support_strength = 1.0
phantom_mass = 0.0

wormhole_azimuthal_m   = {m}
wormhole_rotation_omega = {omega}

L = {L}
N1 = {N}
N2 = {N}
N3 = {N}

center = 32.0 32.0 0.0

max_level = {max_level}
regrid_interval = 32
regrid_threshold = 0.01

max_box_size = 32
min_box_size = 16

isPeriodic = 0 0 0
hi_boundary = 1 1 1
lo_boundary = 1 1 2

nonzero_asymptotic_vars = chi h11 h22 h33 lapse
nonzero_asymptotic_values = 1.0 1.0 1.0 1.0 1.0

dt_multiplier = 0.02
stop_time = {stop_time}

max_spatial_derivative_order = 4
nan_check = 1

min_chi = 1.0e-8
min_lapse = 1.0e-10

lapse_advec_coeff = 1.0
lapse_coeff = 2.0
lapse_power = 1.0

shift_advec_coeff = 1.0
shift_Gamma_coeff = 0.75
eta = 1.0

formulation = 0
kappa1 = 3.0
kappa2 = 0.
kappa3 = 1.
covariantZ4 = 0

sigma = 2.0

puncture_tracking.enabled = 0
calculate_constraint_norms = 1

extraction_center = 32.0 32.0 0.0
activate_extraction = 1
write_extraction = 1
extraction_subpath = "data"

num_extraction_radii = 4
extraction_radii = 12.0 16.0 20.0 24.0
extraction_levels = 0 0 0 0

num_points_phi = 24
num_points_theta = 37
num_modes = 3
modes = 2 0 \\
        2 1 \\
        2 2

amrex.the_arena_init_size = 1048576
amrex.use_gpu_aware_mpi = 0
"""


def render_frames(run_out: Path, jobs: int) -> None:
    env = dict(os.environ)
    env["PYTHONPATH"] = f"{WRAPPER_SRC}:{env.get('PYTHONPATH', '')}"
    cx, cy, cz = CENTER
    cmd = [
        sys.executable, "-m",
        "grteclyn_wrapper.visualisation.process_wave.consume_plotfiles",
        "--data", str(run_out), "--out", str(run_out / "small_data"),
        "--center", str(cx), str(cy), str(cz),
        "--radii", "12", "16", "20", "24", "--n-points", "128",
        "--frames-fields", *FRAME_FIELDS.split(),
        "--frames-axis", "z", "--frames-zoom", "48",
        "--frames-center", "8", "8", "0", "--frames-corner",
        "--frames-global-zlim", "--frames-out", str(run_out / "frames"),
        "-j", str(jobs),
    ]
    subprocess.run(cmd, env=env, check=True)


def prune_plotfiles(run_out: Path) -> None:
    for d in list(run_out.glob("RotatingWormholePlt*")) + list(
        run_out.glob("RotatingWormholeChk*")
    ):
        if d.is_dir():
            subprocess.run(["rm", "-rf", str(d)], check=False)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--kappa", type=float, required=True)
    ap.add_argument("--dx", type=float, default=0.5, choices=[0.5, 1.0])
    ap.add_argument("--omega", type=float, default=0.05)
    ap.add_argument("--m", type=int, default=1)
    ap.add_argument("--max-level", type=int, default=3)
    ap.add_argument("--stop-time", type=float, default=8.0)
    ap.add_argument("--plot-interval", type=int, default=40)
    ap.add_argument("--gpu", type=int, default=0)
    ap.add_argument("--gridinit", default=None, help="override ID .gridinit path")
    ap.add_argument("--frames", dest="frames", action="store_true", default=True)
    ap.add_argument("--no-frames", dest="frames", action="store_false")
    ap.add_argument("--frame-jobs", type=int, default=32)
    ap.add_argument("--keep-plotfiles", action="store_true",
                    help="do not prune plotfiles after frame extraction")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    N = int(round(EVO_L / args.dx))
    gridinit = (
        Path(args.gridinit).resolve()
        if args.gridinit
        else ID_ROOT / id_tag(args.kappa, args.omega, args.m, args.dx)
        / "initial_data.gridinit"
    )
    if not gridinit.is_file():
        print(f"error: gridinit not found: {gridinit}\n"
              f"       solve it first: RES_N={N} solve_kappa_family.sh {args.kappa}",
              file=sys.stderr)
        return 2
    if not BIN.exists():
        print(f"error: CUDA binary not found: {BIN}", file=sys.stderr)
        return 2

    tag = case_tag(args.kappa, args.omega, args.m, args.dx, args.max_level)
    run_dir = RUN_ROOT / tag
    run_out = run_dir / "output"
    run_out.mkdir(parents=True, exist_ok=True)

    # GRTeclyn resolves relative paths against its cwd (the example dir); use the
    # absolute run path so the generated params are location-independent.
    params_text = PARAMS_TEMPLATE.format(
        m=args.m, omega=args.omega, kappa=args.kappa, dx=args.dx, N=N, L=EVO_L,
        max_level=args.max_level, stop_time=args.stop_time,
        plot_interval=args.plot_interval, run_out=str(run_out),
        gridinit=str(gridinit),
    )
    params_path = run_dir / "params.txt"
    params_path.write_text(params_text)
    print(f"[wormhole_case] {tag}")
    print(f"  gridinit: {gridinit}")
    print(f"  params:   {params_path}")
    print(f"  N={N} dx={args.dx} max_level={args.max_level} "
          f"stop_time={args.stop_time} gpu={args.gpu}")
    if args.dry_run:
        return 0

    env = dict(os.environ)
    env["CUDA_VISIBLE_DEVICES"] = str(args.gpu)
    log = run_dir / "evolve.log"
    print(f"  running -> {log}")
    with log.open("w") as fh:
        subprocess.run([str(BIN), str(params_path)], cwd=str(EXAMPLE_DIR),
                       env=env, stdout=fh, stderr=subprocess.STDOUT, check=True)

    if args.frames:
        print("  rendering frames (offline)...")
        render_frames(run_out, args.frame_jobs)
        if not args.keep_plotfiles:
            prune_plotfiles(run_out)
            print("  pruned plotfiles (frames + data kept)")
    print(f"[wormhole_case] done: {run_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
