version: 2
updates:
  # Enable version updates for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  # Enable version updates for git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      # Check for updates to gii submodules every week
      interval: "weekly"