variables:
  MODULES_DAWN: >
    default-dawn
    dawn-env/2024-12-29
    intel-oneapi-compilers/2025.0.4/gcc/umo7dwbo
    intel-oneapi-mpi/2021.14.1/
    intel-oneapi-mkl/2025.0.1/
  SYCL_BUILD_CONFIG: >
    USE_SYCL=TRUE
    SYCL_AOT=TRUE
    DEBUG=TRUE
    TEST=TRUE
    USE_ASSERTION=TRUE
    SYCL_SUB_GROUP_SIZE=16
    SYCL_AOT_GRF_MODE=Large


stage: test
tags:
  - csd3
script:
  - if [[ -d ../amrex ]]; then
  -   cd ../amrex
  -   git fetch --depth 1
  -   git reset --hard origin/development
  - else
  -   git clone --depth 1 https://github.com/AMReX-Codes/amrex.git ../amrex
  - fi
  - AMREX_HOME="$PWD"
  - module purge
  - module load ${MODULES_DAWN}
  - cd ${AMREX_HOME}/Tools/Plotfile    
  - srun -A ZETTASCALE-PORTING-DAWN-GPU -p pvc --nodes=1 --ntasks=1 --time=00:10:00 --gres=gpu:1 make -j 8 COMP=intel-llvm programs=fcompare
  - cd ${HOME}/${CI_PROJECT_DIR}/Tests
  - srun -A ZETTASCALE-PORTING-DAWN-GPU -p pvc --nodes=1 --ntasks=1 --time=00:10:00 --gres=gpu:1 make run ${SYCL_BUILD_CONFIG}
  
