stages:
  - test

variables:
  MODULEPATHS_A100: >
    /usr/local/software/spack/spack-modules/a100-20210927/linux-centos8-zen2
    /usr/local/software/spack/spack-modules/a100-20210927/linux-centos8-zen3
  # The OpenMPI module has a CUDA dependency so will autoload a module for it
  MODULES_A100: >
    rhel8/slurm
    rhel8/global
    openmpi/4.1.1/gcc-9.4.0-epagguv
    gcc/9.4.0/gcc-11.2.0-72sgv5z
    hdf5/1.12.1
  BUILD_CONFIG: >
    USE_CUDA=TRUE
    CUDA_ARCH=80
    COMP=gnu
    DEBUG=TRUE
    TEST=TRUE
    USE_ASSERTION=TRUE
    USE_HDF5=TRUE
  SRUN_FLAGS: > 
    --qos=INTR 
    --nodes=1 
    --ntasks=1 
    --gres=gpu:1 
    --time=00:10:00 
    --account=SHELLARD-SL3-GPU 
    --partition=ampere
  FCOMPARE_FLAGS: >
    --abs_tol 1e-10
    --rel_tol 1e-10
    --abort_if_not_all_found
  LOCKED_FILENAME: >
    file.lock


csd3-a100:
  stage: test
  tags:
    - csd3
  script:
    - module purge
    - module use ${MODULEPATHS_A100}
    - module load ${MODULES_A100}
    - if [[ -d ../amrex ]]; then
    -   cd ../amrex
    -   git fetch --depth 1
    -   git reset --hard origin/development
    - else
    -   git clone --depth 1 https://github.com/AMReX-Codes/amrex.git ../amrex
    - fi
    - AMREX_HOME="$PWD"
    - cd ${AMREX_HOME}/Tools/Plotfile
    - make -j 8 COMP=gnu programs=fcompare
    - cd ${HOME}/${CI_PROJECT_DIR}/Tests
    - make -j 8 ${BUILD_CONFIG} 
    - flock ${HOME}/${CI_PROJECT_DIR}/${LOCKED_FILENAME} srun ${SRUN_FLAGS} make run ${BUILD_CONFIG}
    - cd ${HOME}/${CI_PROJECT_DIR}/Examples/BinaryBH
    - make -j 8 ${BUILD_CONFIG} USE_HDF5=FALSE
    - flock ${HOME}/${CI_PROJECT_DIR}/${LOCKED_FILENAME} srun ${SRUN_FLAGS} ./main3d.gnu.DEBUG.MPI.CUDA.ex ./params_test.txt
    - ${AMREX_HOME}/Tools/Plotfile/fcompare.gnu.ex ${FCOMPARE_FLAGS} plt00008 ${HOME}/${CI_PROJECT_DIR}/.github/workflows/data/plt00008_compare/
  after_script:
    - rm -rf ${HOME}/${CI_PROJECT_DIR}/${LOCKED_FILENAME}
    
    

