site_name: GRTeclyn
nav:
  - Home: home.md
  - Capabilities: capabilities.md
  - Prerequisites: prerequisites.md
  - Building and running on CPUs: building_cpus.md
  - Building and running on GPUs: building_gpus.md
  - Example configs for specific HPC systems: example_configs.md
  - Examples: examples.md
  - Moving from GRChombo: moving_from_grchombo.md
  - Code structure: code_structure.md
#  - Visualizations: viz.md
  - Performance optimisation: performance_optimisation.md
  - Convergence testing: convergence_testing.md
  - Useful resources: useful_resources.md
  - License and citation: license_and_citation.md
#  - Pull requests:
#  - Updating the wiki:
#  - Coding conventions:
  - Contact us: contact_us.md
theme: readthedocs
