#!/usr/bin/env python3
"""Single-case rotating-wormhole evolution driver (CLI, no per-case param files).

Mirrors the QD-campaign pattern: instead of committing a params_*.txt per case,
this generates the evolution params from one in-code template + CLI knobs, writes
it into the run directory, launches the GRTeclyn CUDA binary, and (optionally)
renders frames offline then prunes the heavy plotfiles.

The GRTresna-solved initial data is located by the same tag scheme the ID driver
(`solve_kappa_family.py`) writes:

    runs/rotating_wormhole_id/rotwh_omega_p<omega>_m<m>_kappa_<kappa>_dx<dx>/initial_data.gridinit

L2 lesson: the evolution level-0 dx must equal the gridinit's native dx, so
--dx selects BOTH (dx=1.0 -> N=64 solve, dx=0.5 -> N=128 solve).

--box-size L controls the domain size (default 64).  A larger box pushes the
Sommerfeld boundary farther from the throat; used for the resolution / boundary
convergence study (is the t~5 dispersal physical or a boundary artifact?).

The stop-time auto-scales with the outermost extraction radius when not
explicitly set: stop_time = r_outer + 6 (light-crossing to the shell plus a
buffer for signal development).  Extraction uses 2 radii (inner fixed at 12,
outer at L/2 - 8) to keep the consumer lightweight.

--mass mu adds a confining potential V = 0.5 mu^2 |Phi|^2 to the phantom scalar
(default 0 = massless ghost, which disperses). A nonzero mass binds the phantom
cloud into a soliton so the throat keeps its support. The ID must be solved with
the SAME mass: `MASS=<mu> solve_kappa_family.sh` (the potential convention
V=0.5 m^2 phi^2 is shared by both codes).

Usage:
    wormhole_case.sh --kappa 1.0 --dx 0.5 --max-level 3 --stop-time 8 --gpu 0
    wormhole_case.sh --kappa 0.7 --dx 0.5 --gpu 1 --no-frames
    wormhole_case.sh --kappa 1.0 --dx 0.5 --box-size 96 --gpu 0   # larger box
    wormhole_case.sh --kappa 1.0 --dx 0.5 --mass 0.1 --gpu 0      # confined
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

GRTECLYN_ROOT = Path(
    os.environ.get("GRTECLYN_ROOT", "/home/jovyan/nachevsky/test/simulation/GRTeclyn")
).resolve()
EXAMPLE_DIR = GRTECLYN_ROOT / "Examples" / "RotatingWormholeCollapse"
ID_ROOT = GRTECLYN_ROOT / "runs" / "rotating_wormhole_id"
RUN_ROOT = GRTECLYN_ROOT / "runs" / "rotating_wormhole"
BIN = EXAMPLE_DIR / "main3d.gnu.MPI.CUDA.ex"
WRAPPER_SRC = Path(__file__).resolve().parents[3] / "src"

DEFAULT_L = 64.0
FRAME_FIELDS = "chi chi_minus_1 K lapse phi Pi phi2 Pi2 Weyl4_Re Weyl4_Im Weyl4_Mag"


def _p(x: float) -> str:
    """GRTeclyn-run tag formatting: 0.05 -> '0p05', 1.0 -> '1p00'."""
    return f"{x:.2f}".replace(".", "p")


def _dx_tag(dx: float) -> str:
    return f"dx{dx:.3g}".replace(".", "p")


def _L_suffix(L: float) -> str:
    """Append _L<val> only when L differs from the default (backward compat)."""
    if abs(L - DEFAULT_L) < 0.1:
        return ""
    return f"_L{int(L)}"


def _mass_suffix(mass: float) -> str:
    """Append _mass<val> only when mass>0 (backward compat with massless runs)."""
    if mass <= 0.0:
        return ""
    return f"_mass{mass:g}".replace(".", "p")


def id_tag(kappa: float, omega: float, m: int, dx: float,
           L: float = DEFAULT_L, mass: float = 0.0) -> str:
    # Must match solve_kappa_family.py's run_dir tag.
    return (f"rotwh_omega_p{_p(omega)}_m{m}_kappa_{_p(kappa)}"
            f"_{_dx_tag(dx)}{_L_suffix(L)}{_mass_suffix(mass)}")


def case_tag(kappa: float, omega: float, m: int, dx: float,
             max_level: int, L: float = DEFAULT_L, mass: float = 0.0) -> str:
    return (f"evo_omega_p{_p(omega)}_m{m}_kappa_{_p(kappa)}"
            f"_{_dx_tag(dx)}_ml{max_level}{_L_suffix(L)}{_mass_suffix(mass)}")


def extraction_radii(L: float) -> tuple[float, float]:
    """Two extraction shells: inner fixed at 12, outer as far as L/2 - 8."""
    r_inner = 12.0
    r_outer = L / 2.0 - 8.0
    # Clamp: outer must exceed inner, and stay >= 16 for any reasonable box.
    r_outer = max(r_outer, r_inner + 4.0)
    return (r_inner, r_outer)


def default_stop_time(L: float) -> float:
    """stop_time = r_outer + 6: light-crossing to the outermost extraction
    shell plus a buffer for signal development."""
    _, r_outer = extraction_radii(L)
    return r_outer + 6.0


def regrid_interval_str(max_level: int) -> str:
    """AMReX ParmParse wants one regrid_interval entry per level.

    max_level=0 is unigrid (no regridding). For AMR, coarse levels regrid every
    32 steps, finer levels every 16 (matches SupportedWormholeCollapse params).
    """
    if max_level <= 0:
        return "0"
    base = [32, 32, 16, 16, 16, 16]
    vals = (base + [16] * max_level)[:max_level]
    return " ".join(str(v) for v in vals)


PARAMS_TEMPLATE = """\
# Rotating-wormhole evolution (generated by wormhole_case.py; do not hand-edit).
# GRTresna-solved complex phantom-scalar ID, m={m}, omega={omega}, kappa={kappa}.
# Level-0 dx={dx} (N={N}, L={L}) == gridinit native dx (L2). max_level={max_level}.
verbosity = 1

output_path = "{run_out}"
amr.check_file = "{run_out}/RotatingWormholeChk"
amr.plot_file  = "{run_out}/RotatingWormholePlt"

checkpoint_interval = -1
plot_interval       = {plot_interval}

amr.plot_vars = chi K lapse shift1 shift2 shift3 phi Pi phi2 Pi2
amr.derive_plot_vars = Weyl4

hdf5_subpath = "hdf5"
pout_subpath = "pout"
data_subpath = "data"

print_progress_only_to_rank_0 = 1

recipe_initial_data_file = "{gridinit}"
wormhole_matter_model = "complex_scalar"

wormhole_initial_lapse_type = 0
wormhole_throat_radius = 0.5
wormhole_centerA = 0.0 0.0 0.0
wormhole_phi_monopole_amplitude     = 0.0
wormhole_phi_perturbation_amplitude = 0.0
wormhole_phi_perturbation_width     = 0.5
wormhole_support_strength = 1.0
phantom_mass = {mass}

wormhole_azimuthal_m   = {m}
wormhole_rotation_omega = {omega}

L = {L}
N1 = {N}
N2 = {N}
N3 = {N}

center = {center_x} {center_y} {center_z}

max_level = {max_level}
regrid_interval = {regrid_interval}
regrid_threshold = 0.01

max_box_size = 32
min_box_size = 16

isPeriodic = 0 0 0
hi_boundary = 1 1 1
lo_boundary = 1 1 2

nonzero_asymptotic_vars = chi h11 h22 h33 lapse
nonzero_asymptotic_values = 1.0 1.0 1.0 1.0 1.0

dt_multiplier = 0.02
stop_time = {stop_time}

max_spatial_derivative_order = 4
nan_check = 1

min_chi = 1.0e-8
min_lapse = 1.0e-10

lapse_advec_coeff = 1.0
lapse_coeff = 2.0
lapse_power = 1.0

shift_advec_coeff = 1.0
shift_Gamma_coeff = 0.75
eta = 1.0

formulation = 0
kappa1 = 3.0
kappa2 = 0.
kappa3 = 1.
covariantZ4 = 0

sigma = 2.0

puncture_tracking.enabled = 0
calculate_constraint_norms = 1

extraction_center = {center_x} {center_y} {center_z}
activate_extraction = 1
write_extraction = 1
extraction_subpath = "data"

num_extraction_radii = {num_extraction_radii}
extraction_radii = {extraction_radii_str}
extraction_levels = {extraction_levels_str}

num_points_phi = 24
num_points_theta = 37
num_modes = 3
modes = 2 0 \\
        2 1 \\
        2 2

amrex.the_arena_init_size = 1048576
amrex.use_gpu_aware_mpi = 0
"""


def _consumer_env() -> dict:
    env = dict(os.environ)
    env["PYTHONPATH"] = f"{WRAPPER_SRC}:{env.get('PYTHONPATH', '')}"
    # The consumer is CPU-only; keep it off the evolution GPU.
    env.pop("CUDA_VISIBLE_DEVICES", None)
    return env


# Module-level state set by main() before any consumer call.
_run_center: tuple[float, float, float] = (32.0, 32.0, 0.0)
_run_radii: tuple[float, ...] = (12.0, 24.0)
_run_L: float = DEFAULT_L


def _consumer_cmd(run_out: Path, jobs: int, *, watch: bool,
                  delete: bool, keep_last: int,
                  keep_existing_frames: bool = False) -> list[str]:
    cx, cy, cz = _run_center
    # Frame zoom: cover the inner ~75% of the box so the boundary is cropped.
    zoom = _run_L * 0.75
    # Frame center offset from the lower-left corner (the consumer's
    # --frames-corner mode places origin at (0,0,0) of the plotfile).
    fc_x = cx - zoom / 2.0
    fc_y = cy - zoom / 2.0
    cmd = [
        sys.executable, "-m",
        "grteclyn_wrapper.visualisation.process_wave.consume_plotfiles",
        "--data", str(run_out), "--out", str(run_out / "small_data"),
        "--center", str(cx), str(cy), str(cz),
        "--radii", *(str(r) for r in _run_radii), "--n-points", "128",
        "--frames-fields", *FRAME_FIELDS.split(),
        "--frames-axis", "z", "--frames-zoom", str(zoom),
        "--frames-center", str(fc_x), str(fc_y), "0", "--frames-corner",
        "--frames-global-zlim", "--frames-out", str(run_out / "frames"),
        "-j", str(jobs),
    ]
    if delete:
        cmd += ["--delete", "--keep-last", str(keep_last)]
    if watch:
        cmd += ["--watch", "--poll-seconds", "15"]
    if keep_existing_frames:
        # Consumer deletes existing frames at startup by default; a post-run
        # drain MUST preserve the frames the live sidecar already rendered.
        cmd += ["--keep-existing-frames"]
    return cmd


def start_frame_consumer(run_out: Path, jobs: int,
                         keep_last: int = 3) -> subprocess.Popen:
    """Streaming sidecar (L6 disk discipline): render frames + Psi4 and delete
    plotfiles *during* the evolution, keeping only the newest `keep_last` for
    safety. --frames-global-zlim locks the colorbar from the first (t=0) plotfile.
    """
    return subprocess.Popen(
        _consumer_cmd(run_out, jobs, watch=True, delete=True, keep_last=keep_last),
        env=_consumer_env(),
    )


def render_frames(run_out: Path, jobs: int) -> None:
    """One-shot render that keeps plotfiles (used only with --keep-plotfiles)."""
    subprocess.run(
        _consumer_cmd(run_out, jobs, watch=False, delete=False, keep_last=0),
        env=_consumer_env(), check=True,
    )


def drain_frames(run_out: Path, jobs: int) -> None:
    """One-shot post-run pass: process any stragglers the sidecar didn't reach
    (its keep_last tail) and delete every remaining plotfile."""
    subprocess.run(
        _consumer_cmd(run_out, jobs, watch=False, delete=True, keep_last=0,
                      keep_existing_frames=True),
        env=_consumer_env(), check=False,
    )


def prune_plotfiles(run_out: Path) -> None:
    for d in list(run_out.glob("RotatingWormholePlt*")) + list(
        run_out.glob("RotatingWormholeChk*")
    ):
        if d.is_dir():
            subprocess.run(["rm", "-rf", str(d)], check=False)


def main() -> int:
    global _run_center, _run_radii, _run_L

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--kappa", type=float, required=True)
    ap.add_argument("--dx", type=float, default=0.5, choices=[0.5, 1.0])
    ap.add_argument("--omega", type=float, default=0.05)
    ap.add_argument("--m", type=int, default=1)
    ap.add_argument("--max-level", type=int, default=3)
    ap.add_argument("--stop-time", type=float, default=None,
                    help="evolution stop time (default: r_outer + 6)")
    ap.add_argument("--box-size", type=float, default=DEFAULT_L,
                    help="domain side length L (default 64); larger box for "
                         "boundary convergence study")
    ap.add_argument("--mass", type=float, default=0.0,
                    help="phantom scalar field mass mu (default 0 = massless "
                         "ghost). >0 adds a confining potential V=0.5 mu^2|Phi|^2 "
                         "so the throat keeps its support; must match the ID "
                         "solved with MASS=<same> solve_kappa_family.sh")
    ap.add_argument("--plot-interval", type=int, default=40)
    ap.add_argument("--gpu", type=int, default=0)
    ap.add_argument("--gridinit", default=None, help="override ID .gridinit path")
    ap.add_argument("--frames", dest="frames", action="store_true", default=True)
    ap.add_argument("--no-frames", dest="frames", action="store_false")
    # NFS plotfiles are large (~GB at N=128/ml=3); -j>4 thrashes the network
    # and hangs (see scripts/plot/drain_plotfiles_frames.sh). Keep it modest,
    # especially when several cases render concurrently.
    ap.add_argument("--frame-jobs", type=int, default=4)
    ap.add_argument("--keep-plotfiles", action="store_true",
                    help="do not prune plotfiles after frame extraction")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    L = args.box_size
    N = int(round(L / args.dx))
    center = (L / 2.0, L / 2.0, 0.0)
    radii = extraction_radii(L)
    stop_time = args.stop_time if args.stop_time is not None else default_stop_time(L)

    # Publish to module state so the consumer helpers pick them up.
    _run_center = center
    _run_radii = radii
    _run_L = L

    gridinit = (
        Path(args.gridinit).resolve()
        if args.gridinit
        else ID_ROOT / id_tag(args.kappa, args.omega, args.m, args.dx, L, args.mass)
        / "initial_data.gridinit"
    )
    if not gridinit.is_file():
        hint = " ".join(
            ([f"EVO_L={int(L)} RES_N={N}"] if L != DEFAULT_L else [f"RES_N={N}"])
            + ([f"MASS={args.mass:g}"] if args.mass > 0 else [])
        )
        print(f"error: gridinit not found: {gridinit}\n"
              f"       solve it first: {hint} solve_kappa_family.sh {args.kappa}",
              file=sys.stderr)
        return 2
    if not BIN.exists():
        print(f"error: CUDA binary not found: {BIN}", file=sys.stderr)
        return 2

    tag = case_tag(args.kappa, args.omega, args.m, args.dx, args.max_level, L, args.mass)
    run_dir = RUN_ROOT / tag
    run_out = run_dir / "output"
    run_out.mkdir(parents=True, exist_ok=True)

    cx, cy, cz = center
    radii_str = " ".join(f"{r:.1f}" for r in radii)
    levels_str = " ".join("0" for _ in radii)

    # GRTeclyn resolves relative paths against its cwd (the example dir); use the
    # absolute run path so the generated params are location-independent.
    params_text = PARAMS_TEMPLATE.format(
        m=args.m, omega=args.omega, kappa=args.kappa, dx=args.dx, N=N, L=L,
        mass=args.mass,
        center_x=cx, center_y=cy, center_z=cz,
        max_level=args.max_level, stop_time=stop_time,
        plot_interval=args.plot_interval, run_out=str(run_out),
        gridinit=str(gridinit),
        regrid_interval=regrid_interval_str(args.max_level),
        num_extraction_radii=len(radii),
        extraction_radii_str=radii_str,
        extraction_levels_str=levels_str,
    )
    params_path = run_dir / "params.txt"
    params_path.write_text(params_text)
    print(f"[wormhole_case] {tag}")
    print(f"  gridinit: {gridinit}")
    print(f"  params:   {params_path}")
    print(f"  L={L} N={N} dx={args.dx} max_level={args.max_level} "
          f"mass={args.mass} stop_time={stop_time} radii={radii} gpu={args.gpu}")
    if args.dry_run:
        return 0

    env = dict(os.environ)
    env["CUDA_VISIBLE_DEVICES"] = str(args.gpu)
    log = run_dir / "evolve.log"

    # Stream frames + Psi4 and delete plotfiles *during* the run so the heavy
    # HDF5 backlog never accumulates (L6). Only the newest few are retained live;
    # a post-run drain handles that tail. --keep-plotfiles falls back to a
    # one-shot offline render that retains the plotfiles.
    consumer = None
    if args.frames and not args.keep_plotfiles:
        print("  starting frame/Psi4 sidecar (stream + delete plotfiles, L6)")
        consumer = start_frame_consumer(run_out, args.frame_jobs)

    print(f"  running -> {log}")
    try:
        with log.open("w") as fh:
            subprocess.run([str(BIN), str(params_path)], cwd=str(EXAMPLE_DIR),
                           env=env, stdout=fh, stderr=subprocess.STDOUT, check=True)
    finally:
        if consumer is not None:
            consumer.terminate()
            try:
                consumer.wait(timeout=120)
            except subprocess.TimeoutExpired:
                consumer.kill()

    if args.frames:
        if args.keep_plotfiles:
            print("  rendering frames (offline, keeping plotfiles)...")
            render_frames(run_out, args.frame_jobs)
        else:
            print("  draining remaining plotfiles (frames + delete)...")
            drain_frames(run_out, args.frame_jobs)
            prune_plotfiles(run_out)
            print("  plotfiles streamed + pruned (frames + data kept)")
    print(f"[wormhole_case] done: {run_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
