#!/usr/bin/env python3
"""Ablate the ADM pieces that carry the candidate-146 null shortcut.

The headline ray fan is re-traced through the archived metric stack several
times.  Each pass keeps the stored spacetime except for one substitution:

  * ``shift off``   beta^i -> 0 at fixed lapse and spatial metric,
  * ``lapse unit``  alpha  -> 1 at fixed shift and spatial metric,
  * ``spatial only`` alpha -> 1 and beta^i -> 0, keeping gamma_ij,
  * ``shift only``  alpha -> 1 and gamma_ij -> delta_ij, keeping beta^i.

Comparing the resulting f_geo against the unmodified baseline separates
frame dragging from slicing and from proper-distance contraction.  The
substitutions are kinematic diagnostics on the stored metric, not solutions
of the constraints.

Also reports the corridor profile of beta^x, whose peak magnitude in the bulk
is quoted in Sec. V.C.

Run:
    cd grteclyn-wrapper
    PYTHONPATH=src python ../research/neuralspacetime/analysis/mechanism_ablation.py
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

import numpy as np

from grteclyn_wrapper.core.site_paths import grteclyn_root
from grteclyn_wrapper.metrics.probes.ftl.evolving_geodesic import (
    _ray_fan_geometry,
    compute_evolving_geodesic_ftl,
)
from grteclyn_wrapper.metrics.probes.ftl.metric_stack_cache import (
    evolving_field_from_metric_stack_cache,
    metric_stack_dir,
)

REPO = grteclyn_root()
PROMOTE = REPO / "runs" / "grtresna_promote"
OUT = REPO / "research" / "neuralspacetime" / "article" / "data"

RUNS = {
    "RM": PROMOTE / "bcma_rm_L128_N256_t30_hq_eval000146",
    "RC": PROMOTE / "bcma_rc_L128_N192_t30_hq_eval000146",
}
T_EMIT = 4.0
AXIS = 0


def adm_split(g: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (alpha^2, beta^i, gamma_ij) for a stack of 4-metrics."""
    gamma = g[..., 1:, 1:]
    beta_low = g[..., 0, 1:]
    beta_up = np.einsum("...ij,...j->...i", np.linalg.inv(gamma), beta_low)
    alpha2 = np.einsum("...i,...i->...", beta_low, beta_up) - g[..., 0, 0]
    return alpha2, beta_up, gamma


def assemble(alpha2: np.ndarray, beta_up: np.ndarray, gamma: np.ndarray) -> np.ndarray:
    """Rebuild g_{mu nu} from (alpha^2, beta^i, gamma_ij)."""
    beta_low = np.einsum("...ij,...j->...i", gamma, beta_up)
    g = np.zeros(gamma.shape[:-2] + (4, 4), dtype=np.float64)
    g[..., 1:, 1:] = gamma
    g[..., 0, 1:] = beta_low
    g[..., 1:, 0] = beta_low
    g[..., 0, 0] = np.einsum("...i,...i->...", beta_low, beta_up) - alpha2
    return g


def variants(g: np.ndarray) -> dict[str, np.ndarray]:
    alpha2, beta_up, gamma = adm_split(g.astype(np.float64))
    unit = np.ones_like(alpha2)
    zero = np.zeros_like(beta_up)
    flat = np.zeros_like(gamma)
    flat[..., 0, 0] = flat[..., 1, 1] = flat[..., 2, 2] = 1.0
    return {
        "baseline": g,
        "shift_off": assemble(alpha2, zero, gamma),
        "lapse_unit": assemble(unit, beta_up, gamma),
        "spatial_only": assemble(unit, zero, gamma),
        "shift_only": assemble(unit, beta_up, flat),
    }


def corridor_profile(field, t: float, n_samples: int = 145) -> tuple[float, ...]:
    """Return corridor (beta^x min, max, absmax, alpha min, max, mean)."""
    start, end, y0, z0, _, _ = _ray_fan_geometry(field, axis=AXIS, n_rays=5)
    beta_samples = []
    alpha_samples = []
    for x in np.linspace(start, end, n_samples):
        g = field.sample_g(np.array([t, x, y0, z0], dtype=float))
        alpha2, beta_up, _ = adm_split(g)
        beta_samples.append(float(beta_up[AXIS]))
        alpha_samples.append(float(np.sqrt(max(alpha2, 0.0))))
    b = np.asarray(beta_samples)
    a = np.asarray(alpha_samples)
    return (
        float(b.min()),
        float(b.max()),
        float(np.abs(b).max()),
        float(a.min()),
        float(a.max()),
        float(a.mean()),
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = [
        "# Mechanism ablation for candidate 146 (t_emit=4, 5-ray fan, x axis)",
        "# Generated by research/neuralspacetime/analysis/mechanism_ablation.py",
        "# f_geo in percent; variants are kinematic substitutions on the stored metric",
        "# Columns: run  variant  f_geo_pct  t_min  n_reached",
    ]
    shift_rows = [
        "",
        "# Corridor profile (y=z=64, x in [56.8,71.2]) for RM",
        "# Columns: t  beta_x_min  beta_x_max  beta_x_absmax"
        "  alpha_min  alpha_max  alpha_mean",
    ]

    for tag, run_dir in RUNS.items():
        cache = metric_stack_dir(run_dir / "small_data")
        field = evolving_field_from_metric_stack_cache(cache)
        if field is None:
            print(f"{tag}: no metric stack at {cache}")
            continue
        print(f"=== {tag} ({cache}) ===")
        for name, g_var in variants(np.asarray(field.g_stack)).items():
            report = compute_evolving_geodesic_ftl(
                dataclasses.replace(field, g_stack=g_var),
                t_emit=T_EMIT,
                n_rays=5,
                axis=AXIS,
            )
            t_min = (
                report.t_arrival - report.t_emit
                if report.t_arrival is not None
                else float("nan")
            )
            print(
                f"  {name:13s} f_geo={100 * report.f_geo:6.2f}%  "
                f"t_min={t_min:7.4f}  reached={report.n_reached}/{report.n_rays}"
            )
            rows.append(
                f"{tag}  {name}  {100 * report.f_geo:.2f}  {t_min:.4f}  "
                f"{report.n_reached}"
            )

        if tag == "RM":
            print("  corridor beta^x and alpha:")
            for t in field.times:
                if t > 16.0:
                    break
                lo, hi, mag, a_lo, a_hi, a_mean = corridor_profile(field, float(t))
                print(
                    f"    t={t:6.2f}  beta^x [{lo:+.4f}, {hi:+.4f}] |max|={mag:.4f}"
                    f"   alpha [{a_lo:.3f}, {a_hi:.3f}] mean={a_mean:.3f}"
                )
                shift_rows.append(
                    f"{t:.2f}  {lo:+.6f}  {hi:+.6f}  {mag:.6f}  "
                    f"{a_lo:.6f}  {a_hi:.6f}  {a_mean:.6f}"
                )

    out_path = OUT / "mechanism_ablation.txt"
    out_path.write_text("\n".join(rows + shift_rows) + "\n", encoding="utf-8")
    print(f"\nwrote {out_path}")


if __name__ == "__main__":
    main()
