#!/usr/bin/env python3
"""Integrate PD-pump work for candidate-146 HQ runs (pump-on RM vs pump-free).

RadialRecipe collapse_diagnostics.dat layout (15 cols): pump_work at index 14.
See grteclyn_wrapper.metrics.diagnostics.collapse._integrate_pump_work.

Usage (from repo root):
  python research/neuralspacetime/analysis/pump_work_budget.py
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
PROMOTE = REPO / "runs" / "grtresna_promote"
ARTICLE_DATA = REPO / "research" / "neuralspacetime" / "article" / "data"

RUNS = {
    "RM_pump_on": PROMOTE / "bcma_rm_L128_N256_t30_hq_eval000146",
    "PF_pump_free": PROMOTE / "bcma_pfrm_L128_N256_t30_hq_eval000146",
}
PUMP_COL = 14  # 0-based; RadialRecipe 15-col layout


def load_rows(path: Path) -> list[list[float]]:
    rows: list[list[float]] = []
    if not path.is_file():
        return rows
    with path.open() as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            try:
                rows.append([float(x) for x in parts])
            except ValueError:
                continue
    return rows


def integrate_pump(rows: list[list[float]], t_max: float | None = None) -> tuple[float, float, float]:
    """Return (E_pump total, E_pump for t<t_max if set, max |pump_work|)."""
    if len(rows) < 2 or len(rows[0]) <= PUMP_COL:
        return 0.0, 0.0, 0.0
    series = [(r[0], r[PUMP_COL]) for r in rows if len(r) > PUMP_COL]
    energy = 0.0
    energy_early = 0.0
    max_abs = 0.0
    for (t0, p0), (t1, p1) in zip(series, series[1:]):
        de = 0.5 * (p0 + p1) * (t1 - t0)
        energy += de
        if t_max is not None and t1 <= t_max:
            energy_early += de
        elif t_max is not None and t0 < t_max < t1:
            # Partial step into the cut.
            a = (t_max - t0) / (t1 - t0)
            p_cut = (1 - a) * p0 + a * p1
            energy_early += 0.5 * (p0 + p_cut) * (t_max - t0)
        max_abs = max(max_abs, abs(p0), abs(p1))
    return energy, energy_early, max_abs


def matter_energy_proxy(rows: list[list[float]]) -> float | None:
    """Crude |rho|-like proxy from early collapse columns when available.

    RadialRecipe 15-col has no rho_sphere; use max of |phi| range columns
    (indices 10/11) as a scale check only.
    """
    if not rows or len(rows[0]) < 12:
        return None
    # Columns 10/11 are phi_min / phi_max in the wormhole/Radial layouts that
    # share the first 14 fields; use |phi_max| at t~0 as a scale.
    return abs(rows[0][11])


def main() -> None:
    ARTICLE_DATA.mkdir(parents=True, exist_ok=True)
    out_path = ARTICLE_DATA / "pump_work_budget.txt"
    lines = [
        "# Pump-work budget for candidate 146",
        "# Generated by research/neuralspacetime/analysis/pump_work_budget.py",
        "# Columns: run  E_pump_total  E_pump_tlt4  max_abs_pump_work  n_rows  status",
    ]
    print("=" * 64)
    print("Pump-work budget (trapezoid integral of pump_work column)")
    print("=" * 64)
    for label, run_dir in RUNS.items():
        path = run_dir / "data" / "collapse_diagnostics.dat"
        rows = load_rows(path)
        if not rows:
            status = "MISSING"
            e_tot = e_early = max_abs = float("nan")
            n = 0
            print(f"{label}: {status} ({path})")
        else:
            e_tot, e_early, max_abs = integrate_pump(rows, t_max=4.0)
            n = len(rows)
            # Heuristic: pump-free should be numerically zero.
            status = "OK"
            if "pump_free" in label and max_abs > 1e-12:
                status = "WARN_NONEZERO"
            elif "pump_on" in label and abs(e_early) < 1e-30 and max_abs < 1e-30:
                status = "WARN_ZERO_ON"
            proxy = matter_energy_proxy(rows)
            print(f"{label}:")
            print(f"  rows={n}  t=[{rows[0][0]:.3f},{rows[-1][0]:.3f}]")
            print(f"  E_pump(total)     = {e_tot:.6e}")
            print(f"  E_pump(t<4)       = {e_early:.6e}")
            print(f"  max|pump_work|    = {max_abs:.6e}")
            if proxy is not None:
                print(f"  |phi_max|(t~0)    = {proxy:.6e}  (scale check)")
            print(f"  status={status}")
        lines.append(
            f"{label}  {e_tot:.6e}  {e_early:.6e}  {max_abs:.6e}  {n}  {status}"
        )

    out_path.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {out_path}")


if __name__ == "__main__":
    main()
