workflow:
# Only run GitLab CI on changes in the following paths
  rules:
    - changes:
        - Examples/**
        - external/**
        - Source/**
        - Tests/**
        - Tools/GNUMake/**
        - .gitlab-ci.yml
        - .gitlab/**
      when: always
    - when: never

stages:
  - build
  - test

variables:
  MODULES_A100: >
    rhel8/ampere/base
    gcc/14.3.0/vlhhcp6m
    openmpi/4.1.8/gcc/hemliivg
    cuda/12.8.1/gcc/kdeps6ab
    hdf5/1.14.5/gcc/openmpi/pr5kb6co
  BUILD_CONFIG: >
    USE_CUDA=TRUE
    CUDA_ARCH=80
    COMP=gnu
    DEBUG=TRUE
    TEST=TRUE
    USE_ASSERTION=TRUE
    USE_HDF5=TRUE
    USE_MPI=TRUE
    USE_CCACHE=TRUE
  SRUN_FLAGS: >
    --qos=INTR
    --nodes=1
    --ntasks=2
    --gres=gpu:1
    --time=00:20:00
    --account=SHELLARD-SL3-GPU
    --partition=ampere
  ERR_TOL_FLAGS: >
    --abs_tol 1e-10
    --rel_tol 1e-10
  # We can only run a single job at a time with --qos=INTR
  QOS_INTR_LOCK_FILE: /rds/project/rds-YVo7YUJF2mk/grteclyn-ci-svc/qos-intr.lock
  OUTPUT_DIR: /rds/project/rds-YVo7YUJF2mk/grteclyn-ci-svc/a100-test-${CI_PIPELINE_ID}/


default:
  before_script:
    - module purge
    - module load ${MODULES_A100}
    # Override system version of hdf5
    - export HDF5_HOME=$(which h5diff | sed 's/bin\/h5diff//')
    - export AMREX_HOME=$(realpath ${HOME}/${CI_PROJECT_DIR}/../amrex)
    - >
      if [[ -d ${AMREX_HOME} ]]; then
        cd ${AMREX_HOME}
        git fetch --depth 1
        git reset --hard origin/development
      else
        git clone --depth 1 https://github.com/AMReX-Codes/amrex.git ${AMREX_HOME}
      fi
    # Set up some environment variables, $HOME not defined in global variable scope
    - export BINARY_DIR=$(realpath ${HOME}/a100-build-${CI_PIPELINE_ID})
    - export COMPARE_DIR=$(realpath ${HOME}/${CI_PROJECT_DIR}/.github/workflows/data)
