name: Check for changes to Source files

# This allows us to exclude certain GitHub actions from running
# if, say, only changes to the documentation are made.
# Simply add this as the first step in your jobs and check the
# return value in subsequent steps. It will return true if any
# of the files in the 'has_changes' variable is true

on:
  workflow_call:
    outputs:
      has_core_changes:
        value: ${{ jobs.check-changes.outputs.has_core_changes }}
      has_example_changes:
        value: ${{ jobs.check-changes.outputs.has_example_changes }}
      has_unit_test_changes:
        value: ${{ jobs.check-changes.outputs.has_unit_test_changes }}

jobs:
  check-changes:
    runs-on: ubuntu-24.04
    outputs:
      has_core_changes: ${{ steps.filter.outputs.has_core_changes }}
      has_example_changes: ${{ steps.filter.outputs.has_example_changes }}
      has_unit_test_changes: ${{ steps.filter.outputs.has_unit_test_changes }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.event_name == 'pull_request' && '' || github.ref }}
          filters: |
            has_core_changes: &core
              - 'Source/**'
              - '.github/**'
              - 'GNUmakefile'
              - 'Tools/GNUMake/**'
            has_example_changes:
              - *core
              - 'Examples/**'
            has_unit_test_changes:
              - *core
              - 'Tests/**'
              - 'external/doctest/**'
