name: Lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpp-linter:
    name: clang-tidy & clang-format
    runs-on: ubuntu-22.04
    env:
      LLVM_VERSION: '17'
      AMREX_HOME: ${{ github.workspace }}/amrex
      BINARYBH_EXAMPLE_DIR: ${{ github.workspace }}/GRTeclyn/Examples/BinaryBH
      TESTS_DIR: ${{ github.workspace }}/GRTeclyn/Tests
      TMP_BUILD_DIR: ${{ github.workspace }}/GRTeclyn/tmp_build_dir

    steps:
    - name: Checkout GRTeclyn
      uses: actions/checkout@v4
      with:
        path: GRTeclyn

    - name: Checkout AMReX
      uses: actions/checkout@v4
      with:
        repository: AMReX-Codes/amrex
        path: amrex

    - name: Update package manager database
      id: update-database
      continue-on-error: true
      run: sudo apt-get update

      # This is quite slow so only do this if the previous command fails
    - name: Update package repository mirrors if necessary
      if: steps.update-database.outcome == 'failure'
      run: |
        sudo gem install apt-spy2
        sudo apt-spy2 fix --commit --launchpad --country=US
        sudo apt-get update

    - name: Install MPICH
      run: |
        sudo apt-get -y --no-install-recommends install libmpich-dev

    - name: Generate config and Determine compiler flags
      id: flags
      run: |
        make COMP=llvm AMReX_Config.H
        echo "mpiflags=$(make print-mpicxx_include_dirs COMP=llvm | tail -n 3 | head -n 1 | sed 's/^.*\ is\ //')" >> $GITHUB_OUTPUT
        echo "cxxflags=$(make print-CXXFLAGS COMP=llvm | tail -n 3 | head -n 1 | sed 's/^.*\ is\ //')" >> $GITHUB_OUTPUT
        echo "cppflags=$(make print-CPPFLAGS COMP=llvm | tail -n 3 | head -n 1 | sed 's/^.*\ is\ //')" >> $GITHUB_OUTPUT
        echo "example_includes=$(make print-includes COMP=llvm | tail -n 3 | head -n 1 | sed 's/^.*\ is\ //')" >> $GITHUB_OUTPUT
        cd ${{ env.TESTS_DIR }}
        # We will get duplicate includes but that's OK
        echo "test_includes=$(make print-includes COMP=llvm | tail -n 3 | head -n 1 | sed 's/^.*\ is\ //')" >> $GITHUB_OUTPUT
      working-directory: ${{ env.BINARYBH_EXAMPLE_DIR }}

    - name: Run clang-tidy and clang-format on modified files
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: 'file' # Clang-Format style
        tidy-checks: '' # Use .clang-tidy file cheks
        repo-root: ${{ github.workspace }}/GRTeclyn
        ignore: External
        version: ${{ env.LLVM_VERSION }}
        files-changed-only: true
        lines-changed-only: false
        extra-args: ${{ join(steps.flags.outputs.*,' ') }}
        # Write a comment to the PR with the output
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
        step-summary: 'true' # Print output in the worflow job summary

    - name: Fail job if checks fail
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1

