name: Check .lint-ignore

on: pull_request

jobs:
  check-lint-ignore:
    name: Check .lint-ignore
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout GRTeclyn
      uses: actions/checkout@v6
      with:
        # Tip from https://stackoverflow.com/a/74268200
        fetch-depth: 2

    - name: Check if any modified files match .lint-ignore
      id: modified-files
      run: |
        git ls-files $(cat .lint-ignore | sed '/^[[:blank:]]*#/d;s/#.*//;/^$/d;') > lint_ignore_expanded
        printf "lint_ignore_matches<<EOF\n%s\nEOF" "$(git diff --name-only HEAD^1 HEAD | grep -F -f lint_ignore_expanded)" >> "$GITHUB_OUTPUT"

    - name: Find existing lint-ignore comment
      if: steps.modified-files.outputs.lint_ignore_matches != ''
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: 'This PR modifies the following files which are ignored by [.lint-ignore](.lint-ignore):'

    - name: Prepare lint-ignore comment body
      if: steps.modified-files.outputs.lint_ignore_matches != ''
      id: comment-body
      run: |
        {
          echo 'body<<EOF'
          echo 'This PR modifies the following files which are ignored by [.lint-ignore](.lint-ignore):'
          echo '```'
          echo "${{ steps.modified-files.outputs.lint_ignore_matches }}"
          echo '```'
          echo 'Please consider removing the corresponding patterns from .lint-ignore so that these files can be linted.'
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Post comment on PR if there are matches
      if: steps.modified-files.outputs.lint_ignore_matches != '' && steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.comment-body.outputs.body }}

    - name: Update comment on PR if there are matches
      if: steps.modified-files.outputs.lint_ignore_matches != '' && steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v5
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: ${{ steps.comment-body.outputs.body }}
