name: Regression Tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  binarybh:
    name: BinaryBH
    runs-on: ubuntu-22.04
    env:
      AMREX_HOME: ${{ github.workspace }}/amrex
      BINARYBH_EXAMPLE_DIR: ${{ github.workspace }}/GRAMReX/Examples/BinaryBH

    steps:
    - name: Checkout AMReX
      uses: actions/checkout@v3
      with:
        repository: AMReX-Codes/amrex
        path: amrex

    - name: Checkout GRAMReX
      uses: actions/checkout@v3
      with:
        path: GRAMReX

    - name: Update package manager database
      id: update-database
      continue-on-error: true
      run: sudo apt-get update

      # This is quite slow so only do this if the previous command fails
    - name: Update package repository mirrors if necessary
      if: steps.update-database.outcome == 'failure'
      run: |
        sudo gem install apt-spy2
        sudo apt-spy2 fix --commit --launchpad --country=US
        sudo apt-get update

    - name: Install MPICH
      run: sudo apt-get -y --no-install-recommends install libmpich-dev

    - name: Set Compilers
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 120
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-12 120
        sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-12 120

    - name: Build BinaryBH example
      run: make -j 4
      working-directory: ${{ env.BINARYBH_EXAMPLE_DIR }}

    - name: Build fcompare tool
      run: make -j 4 
      working-directory: ${{ env.AMREX_HOME }}/Tools/Plotfile

    - name: Run BinaryBH example using test parameters
      run: mpiexec -n 2 ./main3d.gnu.MPI.ex ./params_test.txt
      working-directory: ${{ env.BINARYBH_EXAMPLE_DIR }}

    - name: Compare plotfile from final step with saved plotfile
      run: |
        ${AMREX_HOME}/Tools/Plotfile/fcompare.gnu.ex \
        --abs_tol 1e-10 \
        --rel_tol 1e-10 \
        ${GITHUB_WORKSPACE}/GRAMReX/.github/workflows/data/plt00008_compare \
        ${BINARYBH_EXAMPLE_DIR}/plt00008
