name: Style

on: [push]

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 16
