name: Style

on: [push]

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 16

  copyright-headers:
    name: Check copyright headers
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GRTeclyn
      uses: actions/checkout@v4

    - name: Check copyright headers
      run: |
        ./check_copyright_headers copyright_header
      working-directory: ${{ github.workspace }}/Tools/CopyrightHeaders